apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ybax
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ybax
    app.kubernetes.io/part-of: tkrw-pr712-0075-0046-app
  name: devfile-sample-ybax
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ybax
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ybax
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-ybax@sha256:508d231c2b55a62408f34e6ff363d957ec34397918d1a11477ab1c2dca68f754
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
